### ISSUE TITLE
Unable to match RssShuffleHandle

### ISSUE THREAD

**Issue by HuiboPeng** [uber/RemoteShuffleService#29]
Hi,
I'm trying to use the RSS client with Spark 2.4.1 but it fails to match RssShuffleHandle, the following is the error.
```
scala.MatchError: RssShuffleHandle (shuffleId 0, numMaps: 4107, rssServers: 2 servers), partitionFanout: 1 (of class org.apache.spark.shuffle.RssShuffleHandle)
        at org.apache.spark.shuffle.RssShuffleManager.getWriter(RssShuffleManager.scala:152)
        at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:98)
        at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:55)
        at org.apache.spark.scheduler.Task.run(Task.scala:121)
        at org.apache.spark.executor.Executor$TaskRunner$$anonfun$10.apply(Executor.scala:403)
        at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1360)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:409)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

**Comment by hiboyang** [comment]
Did you enable "spark.driver.userClassPathFirst" or "spark.executor.userClassPathFirst" in your spark application? If so, would you set them to false and try again?

**Comment by HuiboPeng** [comment]
It works, thanks. However, why we enable "spark.driver.userClassPathFirst" or "spark.executor.userClassPathFirst" will lead to application failed. If we want to use user classpath first, how we can fix it.

**Comment by hiboyang** [comment]
The RssShuffleHandle object is serialized in Spark driver, passed to executor and deserialized in executor. If use userClassPathFirst, the class loader may be different when serialize and deserialize the object, thus cause error.
